gui:
    theme:
      activeBorderColor:
        - "#92CEF5"
        - bold
      inactiveBorderColor:
        - "#262A2E"
      optionsTextColor:
        - "#92CEF5"
      selectedLineBgColor:
        - "#1C2024"
      selectedRangeBgColor:
        - "#1C2024"
      cherryPickedCommitFgColor:
        - "#92CEF5"
      cherryPickedCommitBgColor:
        - "#1C2024"
      markedBaseCommitFgColor:
        - "#9DC181"
      markedBaseCommitBgColor:
        - "#1C2024"
      unstagedChangesColor:
        - "#C389D1"
      defaultFgColor:
        - "#DFE3E7"




